### ISSUE TITLE
JSON/XML serialization of unsigned numbers (uint32, uint64, fixed32, fixed64)

### ISSUE THREAD

**Issue by fqqb** [protostuff/protostuff#148]
A message field of type uint32 that actually uses the sign-bit, appears to be serialized to JSON as a negative number.

For example, if the corresponding java int has this value:

    0xFAE15000

protostuff-json will serialize this to a value `-85897216`, whereas it really is `4209070080`.

This caught me by surprise, as I was not expecting that behaviour in a non-binary format like JSON. I can work around it for my use case by doing some post-processing, but was wondering whether it's a deliberate choice on your end.

thanks

**Comment by dyu** [comment]
Not sure if that should be default behavior. 
As a workaround for the moment, you can modify/copy JsonInput's impl and cast the int to long and call writeInt64.
@kshchepanovskyi this behavior can be enabled via an extra bool field in JsonInput or a static bool activated via a system property.

**Comment by fqqb** [comment]
i think you meant to say JsonOutput (my actual consumer is javascript).
Thanks, that looks like a way cleaner workaround than what i was planning to do.

afaik, you also need to apply a bit mask before the writeInt64 to bypass java limitations. As in:

    myUint & 0xFFFFFFFFL

and then some similar things to keep the JsonInput in balance too, i guess.

**Comment by dyu** [comment]
Yeah I meant JsonOutput.

**Comment by kshchepanovskyi** [comment]
Ok, I will take a look. But this issue is more general - it should be solved for `uint64` as well.

**Comment by kshchepanovskyi** [comment]
@dyu 

I think it should be default behavior, and we should treat this as a "bug". I understand that it breaks compatibility, but it should be fixed. Note about possible compatibility issues will be added to release notes.

As for me, it is bad idea (in long term) to add flags for enabling such fixes. It adds too much complexity - users need to learn about all these hidden "options".

In order to make migration easier, we can make parser accept negative numbers. This way we can keep it compatible with data serialized by older protostuff version.

**Comment by kshchepanovskyi** [comment]
Also it affects XML serialization / deserialization.

**Comment by kshchepanovskyi** [comment]
@dyu 

*Upd: there is a a solution for compatibility issue.* 

Technically, we can say that serialization/deserialization for `uint32`/`uint64`/`fixed32`/`fixed64` before this fix was done as these fields always was signed. As a result, in order to fix compatibility issue, all such fields in proto files should be changed to their corresponding signed types.

**Comment by dyu** [comment]
Making it default is ok as long as its on a major version change and as you said, reflected on the release notes about compatibility.
For the current minor version, the sysprops setting could be the workaround.

**Comment by kshchepanovskyi** [comment]
Major - do you mean 1.4 or 2.0?

On Mon, Feb 1, 2016 at 3:58 AM, David Yu <notifications@github.com> wrote:

> Making it default is ok as long as its on a major version change and as
> you said, reflected on the release notes about compatibility.
> For the current minor version, the sysprops setting could be the
> workaround.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/protostuff/protostuff/issues/148#issuecomment-177699643>
> .
>



-- 
Regards,

Konstantin

**Comment by dyu** [comment]
1.4
