### ISSUE TITLE
Message 'Message' seems causing a conflict with io.protostuff.Message.

### ISSUE THREAD

**Issue by cosmir17** [protostuff/protostuff#170]
If I have something like the following, there would be an issue.

```proto
message Message {
	required string messageId = 1;
}
```

Cheers
Seong

**Comment by kshchepanovskyi** [comment]
Hi.

Will gladly accept a pull request that fixes this issue.

It can be fixed by changing code generator to use FQN - `io.protostuff.Message` instead of `Message` + import. In general, it is safer to do not use imports in generated code at all.

P.S. This issue is already fixed this in [new major protostuff-compiler version](https://github.com/protostuff/protostuff-compiler), but is not finished yet.

**Comment by cosmir17** [comment]
Thank you for the valuable information.
I am also glad that it's already been fixed.

Cheers
Seong
