### ISSUE TITLE
How to support null elements in collection or arrays?

### ISSUE THREAD

**Issue by jackeylu** [protostuff/protostuff#192]
Hi all, I am bumped in a problem of null elements in collection and arrays. The List or Set collection after deserialized,  null elements will be lost. And in array's case, null elements will lost their original orders.

I hope to use protostuff to ser/deser objects produced by a thrid-party system, I think I am not able to add any special value to denote null (I think #165 is similar with my case, but I can't use its solution).  Am I using protostuff in a wrong way? or the protostuff is not suitable for my case?

I post the entire example codes in the gist, https://gist.github.com/jackeylu/3fa72264ca7de02f7030d0ed7b98a3e4 
My problem can be easily produced by the unit tests.

Thank you very much.

**Comment by dyu** [comment]
Null elements on collections being excluded on serialization was by design (protobuf semantics).

One can make it work by adding a parallel implementation of CollectionSchema (and IdStrategy's nested anonymous classes) like how it is done in ArraySchemas and choosing that impl based on IdStrategy flags (deferred binding, so shouldn't affect runtime performance much).

Having said that, that's quite a lot of work when other libraries would already support your usecase (unless you're after protostuff-graph's performance).

**Comment by jackeylu** [comment]
@dyu Thank you, I understood.

**Comment by mikaelgrev** [comment]
Oh, bummer. I finally tracked down why an sparse array wasn't deserialized correctly with protostuff. I must I am very surprised that arrays doesn't come back as they were put in (Java has the notion of null in arrays and lists, even if Google doesn't like it) and there are no warnings. For me this means I must opt out of protostuff since I use a lot of sparse lists/arrays. :(
