### ISSUE TITLE
Protostuff compiler fails on map definition

### ISSUE THREAD

**Issue by pappist** [protostuff/protostuff#205]
I am trying to generate Java POJOs with protostuff compiler using the maven plugin, but it fails on map definitions and does not generate the map fields. 
I got the following errors: 
```
line 12:4 no viable alternative at character '<'
line 12:1 mismatched input 'map' expecting RIGHTCURLY
```
I use proto2 syntax and protostuff 1.5.2. Maybe there is a bug in protostuff parser?

**Comment by kshchepanovskyi** [comment]
Hi @pappist,

There is a new version of parser and code generator: https://github.com/protostuff/protostuff-compiler
It supports both proto2 and proto3 sources. However, generated code is different to what old compiler generates - they are more like code that `protoc` generates with `java_out` output, but compatible with protostuff 1.5 library.

**Comment by pappist** [comment]
Hi @kshchepanovskyi,

Thanks for the quick reply! It seems to work!
Can I use the same compiler options as with the [old version](http://www.protostuff.io/documentation/compiler-options/)? 
I only need to redefine the java packages for compiled output.

Thanks a lot!

**Comment by kshchepanovskyi** [comment]
No, I afraid that's not possible.

However, new generator is much more flexible than old one - but in order to customize something, you have to use `st4` maven goal and custom ST4 template (templates support inheritance, so you need to override only some parts of them).

I can help you with customization - please create a simple maven project, and explain what do you need to be changed in the generated code.

**Comment by kshchepanovskyi** [comment]
Some info is here: https://github.com/protostuff/protostuff-compiler/issues/8#issuecomment-214897449

It will be more formalized and added to wiki later.
